### ISSUE TITLE
online demo please :)?

### ISSUE THREAD

**Issue by winkler1** [buildo/react-input-children#1]
Would like to add to react.rocks, thanks

**Comment by FrancescoCioria** [comment]
is it fine a demo on JSFiddle like this one?
http://jsfiddle.net/FrancescoCioria/0ycfru3n/3/

**Comment by winkler1** [comment]
Sure, thanks

**Comment by FrancescoCioria** [comment]
I also added the link to the demo in the Readme, thanks
