### ISSUE TITLE
Update npmjs live demo and examples URLs

### ISSUE THREAD

**Issue by leotm** [buildo/react-input-children#45]
## description
Links on [npmjs.com/package/react-input-link](https://www.npmjs.com/package/react-input-link) should not 404.

## how to reproduce
Go to [npmjs.com/package/react-input-link](https://www.npmjs.com/package/react-input-link).
Click [Live demo](https://rawgit.com/buildo/react-input-link/master/examples/index.html).
Click more examples [here](more examples here).

**Comment by giogonzo** [comment]
`react-input-link` is the old name of the package, that was never deprecated (I just did it). Please use https://www.npmjs.com/package/react-input-children instead
